### ISSUE TITLE
Add a Review Paper

### ISSUE THREAD

**Issue by iphysresearch** [FeiLiu36/LLM4Opt#10]
I came across this review article: https://arxiv.org/abs/2405.10098. It seems highly relevant and would be a great addition to summarize in this repo.

Would love to hear your thoughts on including it!

Feel free to modify it further if needed!

**Comment by FeiLiu36** [comment]
Thank you very much for your interest in this Rep and for the valuable addition. Actually, this review has already been included in the ["Review Paper" section](https://github.com/FeiLiu36/LLM4Opt#Review).
